### ISSUE TITLE
通过脚本编译安装ycm失败,手动安装ycm成功

### ISSUE THREAD

**Issue by trim21** [hmybmny/vim.cpp#1]
ubuntu 16.04 
python2 2.7.12
python3 3.5.2
vim式自行编译的8.0

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 17 2016 23:29:20)
包含补丁: 1-5
```

```
Vim: 警告: 输入不是来自终端(键盘)
UltiSnips requires py >= 2.7 or py3
YouCompleteMe unavailable: requires Vim compiled with Python (2.6+ or 3.3+) support
请按 ENTER 或其它命令继续
```

现在整个vim每次启动都会报

```
UltiSnips requires py >= 2.7 or py3
YouCompleteMe unavailable: requires Vim compiled with Python (2.6+ or 3.3+) support
请按 ENTER 或其它命令继续
```

**Comment by kingofctrl** [comment]
`YouCompleteMe unavailable: requires Vim compiled with Python (2.6+ or 3.3+) support`
对于这个错误，你打开 `vim` 后输入 `:echo has('python')` 看看输出是不是 `1`，如果是 `0` 的话说明你的 `vim` 不支持 `python` ，需要重新编译安装，编译安装的方法你可以看看这个 https://github.com/HmyBmny/vimrc#building-vim-from-source

`UltiSnips requires py >= 2.7 or py3`
这个提示应该是你的 `python` 版本过低，需要更新到 2.7 以上的版本，如果你的 `python` 版本是 `2.7.12` 的话那可能是 `vim` 不支持  `python` 所引起的错误。

**Comment by trim21** [comment]
是这样的...之前编译的时候指定的python config路径错误了,导致没能开启python支持
